### ISSUE TITLE
issue with a10_router_bgp

### ISSUE THREAD

**Issue by jsmith0012** [a10networks/a10-ansible#36]
seem to be having a issue with the a10_router_bgp.  here is what i got so far

python 2.7.5
ansible 2.7.5

  - name: update a10_router_bgp
    a10_router_bgp:
      a10_host: "asdfasdft"
      a10_username: "admin"
      a10_password: "asdfasdfasdf"
      state: present
      as_number: "64551"

The full traceback is:
Traceback (most recent call last):
  File "/home/jsmith/.ansible/tmp/ansible-tmp-1549393384.87-185129765312972/AnsiballZ_a10_router_bgp.py", line 113, in <module>
    _ansiballz_main()
  File "/home/jsmith/.ansible/tmp/ansible-tmp-1549393384.87-185129765312972/AnsiballZ_a10_router_bgp.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/jsmith/.ansible/tmp/ansible-tmp-1549393384.87-185129765312972/AnsiballZ_a10_router_bgp.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_a10_router_bgp_payload_XB1psn/__main__.py", line 479, in <module>
  File "/tmp/ansible_a10_router_bgp_payload_XB1psn/__main__.py", line 471, in main
  File "/tmp/ansible_a10_router_bgp_payload_XB1psn/__main__.py", line 459, in run_command
  File "/tmp/ansible_a10_router_bgp_payload_XB1psn/__main__.py", line 376, in exists
  File "/tmp/ansible_a10_router_bgp_payload_XB1psn/__main__.py", line 372, in get
  File "/tmp/ansible_a10_router_bgp_payload_XB1psn/__main__.py", line 298, in existing_url
KeyError: 'as-number'

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/jsmith/.ansible/tmp/ansible-tmp-1549393384.87-185129765312972/AnsiballZ_a10_router_bgp.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/jsmith/.ansible/tmp/ansible-tmp-1549393384.87-185129765312972/AnsiballZ_a10_router_bgp.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/jsmith/.ansible/tmp/ansible-tmp-1549393384.87-185129765312972/AnsiballZ_a10_router_bgp.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_a10_router_bgp_payload_XB1psn/__main__.py\", line 479, in <module>\n  File \"/tmp/ansible_a10_router_bgp_payload_XB1psn/__main__.py\", line 471, in main\n  File \"/tmp/ansible_a10_router_bgp_payload_XB1psn/__main__.py\", line 459, in run_command\n  File \"/tmp/ansible_a10_router_bgp_payload_XB1psn/__main__.py\", line 376, in exists\n  File \"/tmp/ansible_a10_router_bgp_payload_XB1psn/__main__.py\", line 372, in get\n  File \"/tmp/ansible_a10_router_bgp_payload_XB1psn/__main__.py\", line 298, in existing_url\nKeyError: 'as-number'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}

**Comment by hthompson6** [comment]
Closing due to age. Please re-open and send email to support@a10networks.com if you are still experiencing this issue.
