### ISSUE TITLE
NameError: name 'module' is not defined

### ISSUE THREAD

**Issue by nerditup** [a10networks/a10-ansible#42]
I am trying to use the A10 Ansible module provided but unfortunately, I keep getting the following Traceback:
 
```
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1551127667.75-151616656537757/AnsiballZ_a10_slb_server.py", line 113, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1551127667.75-151616656537757/AnsiballZ_a10_slb_server.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1551127667.75-151616656537757/AnsiballZ_a10_slb_server.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_a10_slb_server_payload_Rq4EP_/__main__.py", line 230, in <module>
NameError: name 'module' is not defined
 
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1551127667.75-151616656537757/AnsiballZ_a10_slb_server.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1551127667.75-151616656537757/AnsiballZ_a10_slb_server.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1551127667.75-151616656537757/AnsiballZ_a10_slb_server.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_a10_slb_server_payload_Rq4EP_/__main__.py\", line 230, in <module>\nNameError: name 'module' is not defined\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```
 
I am running the following Playbook as a test:
 ```

---
 
- hosts: 'localhost'
  tasks:
    - a10_slb_server:
        a10_host: '10.65.156.202'
        a10_username: 'admin'
        a10_password: '*******'
        host: '10.65.155.122'
        name: 'a10-ansibletest-1'
```
 
From what I can see, it is related to a missing module in the library, but I am unsure how to resolve this. 

Any help would be much appreciated with this.

**Comment by nerditup** [comment]
Ansible needed to be configured to correctly reference this module. I've done the following to make this repository work:

1. Clone this repository into my Ansible project repository, using `./library/a10-ansible/` as the path. 
2. Add the following to my `ansible.cfg` file:
`library = ./library/a10-ansible/a10_ansible`
`module_utils = ./library/a10-ansible/`
